"""
Train an Emergency Dispatch Agent using Unsloth (SFT).
This script loads the 'sft_data.jsonl' generated by collect_sft_data.py
and fine-tunes a model to act in the environment.
"""

import os
import json
from datasets import load_dataset
from unsloth import FastLanguageModel
import torch
from trl import SFTTrainer
from transformers import TrainingArguments

# ── Config ──────────────────────────────────────────────────────────────────
MODEL_NAME = "unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit" # Small & Fast for Hackathon
MAX_SEQ_LENGTH = 2048
DTYPE = None 
LOAD_IN_4BIT = True

# ── Model & Tokenizer ───────────────────────────────────────────────────────
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = MODEL_NAME,
    max_seq_length = MAX_SEQ_LENGTH,
    dtype = DTYPE,
    load_in_4bit = LOAD_IN_4BIT,
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# ── Dataset Loading ─────────────────────────────────────────────────────────
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    outputs      = examples["output"]
    texts = []
    for instruction, input_text, output_text in zip(instructions, inputs, outputs):
        # Format for Qwen/Llama chat
        text = f"<|im_start|>system\n{instruction}<|im_end|>\n"
        text += f"<|im_start|>user\n{input_text}<|im_end|>\n"
        text += f"<|im_start|>assistant\n{output_text}<|im_end|>"
        texts.append(text)
    return { "text" : texts, }

dataset = load_dataset("json", data_files="sft_data.jsonl", split="train")
dataset = dataset.map(formatting_prompts_func, batched = True,)

# ── Training ────────────────────────────────────────────────────────────────
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = MAX_SEQ_LENGTH,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # Small run to prove concept
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

print("Starting SFT Training...")
trainer_stats = trainer.train()

# ── Saving ──────────────────────────────────────────────────────────────────
model.save_pretrained_lora("emergency_dispatch_lora_model")
tokenizer.save_pretrained("emergency_dispatch_lora_model")

print("Training Complete! Model saved to 'emergency_dispatch_lora_model'")
